server:
  port: 8082

spring:
  application:
    name: camera-service
  datasource:
    hikari:
      pool-name: CameraServicePool
      maximum-pool-size: 50 # connections = (core_count * 2) + effective_spindle_count
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 1200000
      connection-timeout: 5000
      leak-detection-threshold: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: 103.163.118.212
      port: 30379
      password: atenergy123
      database: 0

smart:
  sso:
    server-url: http://103.163.118.212:30832
    client-id: 1006
    client-secret: a2775705950e4fa9684c4db00ec2a2d4
    logout-callback-path: /auth/sso/logout-callback
    exclude-urls: /auth/*, /actuator/*
    h5-enabled: true

feign-client:
  peer-service:
    name: peer-service
    url: http://xxx.xxx.xxx.xxx:xxx
    path: /peer